version: "3.8"
services:
  openmp:
    volumes: 
      - ./src:/src
    working_dir: /src
    container_name: openMP-container
    build:
      context: .
      dockerfile: openMPEnv.dockerfile
    cpus: 2
    mem_limit: 2G
    memswap_limit: 4G
    environment: 
      OMP_NUM_THREADS: "4"
    tty: true

